{% set name = "docify" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docify-{{ version }}.tar.gz
  sha256: 8d779f8348dd8d46796709c0db7d710cbc6354935d90a727c9ff3ab77b4cd3bf

build:
  entry_points:
    - docify = docify:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - libcst >=1.1.0
    - tqdm >=4.66.4

test:
  imports:
    - docify
  commands:
    - pip check
    - docify --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AThePeanut4/docify
  summary: A script to add docstrings to Python type stubs using reflection
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
