schema_version: 1

context:
  name: docify
  version: "1.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docify-${{ version }}.tar.gz
  sha256: ed565259a3b20cd754438405b7830e12579f2223bb3c3f13c8e9318c258bc0a8

build:
  number: 0
  noarch: python
  script: uv pip install --python ${{ PYTHON }} . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - docify = docify:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv
  run:
    - python >=${{ python_min }}
    - libcst >=1.1.0
    - tqdm >=4.66.4

tests:
  - python:
      imports:
        - docify
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check
      - docify --help

about:
  summary: A script to add docstrings to Python type stubs using reflection
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/atoerien/docify

extra:
  recipe-maintainers:
    - lucascolley
